// import { HttpStatus, Injectable } from '@nestjs/common';
// import { CreateTodoDto } from './dto/create-todo.dto';
// import { UpdateTodoDto } from './dto/update-todo.dto';
// import { PrismaService } from 'prisma/prisma.service';

// @Injectable()
// export class TodoService {
//   private todo: {
//     id?: number;
//     title: string;
//     description: string;
//     image: string;
//   }[] = [];
//   constructor(private readonly prismaService: PrismaService) {}
//   async create(createTodoDto: CreateTodoDto) {
//     const newTodo = {
//       id?: createTodoDto.id,
//     title: createTodoDto.title,
//     description: createTodoDto.description,
//     image: createTodoDto.
//     }
//     await this.prismaService.todo.create({
//       data: {
//         id?: newTodo.id,
//     title: newTodo.title,
//     description: newTodo.description,
//     image: newTodo.
//       },
//     });
//     return { status: HttpStatus.OK, newTodo };
//   }

//   async findAll() {
//     return await `This action returns all todo`;
//   }

//   async findOne(id: number) {
//     return await `This action returns a #${id} todo`;
//   }

//   async update(id: number, updateTodoDto: UpdateTodoDto) {
//     return await `This action updates a #${id} todo`;
//   }

//   async remove(id: number) {
//     return await `This action removes a #${id} todo`;
//   }
// }

import { HttpStatus, Injectable } from '@nestjs/common';
import { CreateTodoDto } from './dto/create-todo.dto';
import { UpdateTodoDto } from './dto/update-todo.dto';
import { PrismaService } from 'prisma/prisma.service';

@Injectable()
export class TodoService {
  constructor(private readonly prismaService: PrismaService) {}

  async create(createTodoDto: CreateTodoDto) {
    // You don't need to set 'id' since it's auto-generated by Prisma
    const newTodo = await this.prismaService.todo.create({
      data: {
        title: createTodoDto.title,
        description: createTodoDto.description,
        image: createTodoDto.image, // assuming image is a string
      },
    });
    return { status: HttpStatus.CREATED, newTodo };
  }

  async findAll() {
    // Return all todos from the database
    return await this.prismaService.todo.findMany();
  }

  async findOne(id: number) {
    // Return a specific todo by id
    const todo = await this.prismaService.todo.findUnique({
      where: { id },
    });
    if (!todo) {
      return {
        status: HttpStatus.NOT_FOUND,
        message: `Todo with id ${id} not found`,
      };
    }
    return todo;
  }

  async update(id: number, updateTodoDto: UpdateTodoDto) {
    // Update a specific todo by id
    const updatedTodo = await this.prismaService.todo.update({
      where: { id },
      data: updateTodoDto,
    });
    return { status: HttpStatus.OK, updatedTodo };
  }

  async remove(id: number) {
    // Remove a todo by id
    const deletedTodo = await this.prismaService.todo.delete({
      where: { id },
    });
    return { status: HttpStatus.OK, deletedTodo };
  }
}
